# Generated by Django 5.2.5 on 2025-09-30 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo da pessoa que está entrando em contato', max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(help_text='E-mail válido para resposta', max_length=254, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, help_text='Telefone para contato (opcional)', max_length=20, null=True, verbose_name='Telefone')),
                ('assunto', models.CharField(choices=[('geral', 'Informações Gerais'), ('parceria', 'Parceria'), ('projeto', 'Proposta de Projeto'), ('startup', 'Startup/Empreendedorismo'), ('tecnologia', 'Tecnologia e Inovação'), ('outro', 'Outro')], default='geral', help_text='Categoria do contato', max_length=20, verbose_name='Assunto')),
                ('mensagem', models.TextField(help_text='Mensagem detalhada', verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_andamento', 'Em Andamento'), ('respondido', 'Respondido'), ('fechado', 'Fechado')], default='novo', max_length=20, verbose_name='Status')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('resposta', models.TextField(blank=True, help_text='Resposta enviada ao contato', null=True, verbose_name='Resposta')),
                ('ip_origem', models.GenericIPAddressField(blank=True, help_text='IP do usuário que enviou o contato', null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, help_text='Informações do navegador', null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
