# Generated by Django 4.2 on 2025-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoQuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sessao', models.CharField(default='Quem Somos', max_length=100, verbose_name='Nome da Sessão')),
                ('titulo_principal', models.CharField(default='Somos um Hub de Inovação da', max_length=200, verbose_name='Título Principal')),
                ('titulo_azul', models.CharField(default='SECTIDE Nova Friburgo', max_length=100, verbose_name='Título em Azul')),
                ('paragrafo_1', models.TextField(default='Atuamos no desenvolvimento científico, tecnológico, econômico e na transformação digital de Nova Friburgo. Acreditamos que iniciativas em inovação, startups e empresas de base tecnológica constroem alicerces sólidos rumo à CIDADE INTELIGENTE. Projetos que unem ciência, tecnologia e empreendedorismo são a base para um futuro conectado, sustentável e inclusivo.', verbose_name='Primeiro Parágrafo')),
                ('paragrafo_2', models.TextField(default='<strong style="color: #1e40af;">PONTI - Hub de Inovação</strong> é a <strong style="color: #1e40af;">BASE DE LANÇAMENTO DE FOGUETES</strong> da Secretária Municipal de Ciência, Tecnologia, Inovação e Desenvolvimento Econômico de Nova Friburgo.', verbose_name='Segundo Parágrafo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sessoes/quem_somos/', verbose_name='Imagem da Sessão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sessão - Quem Somos',
                'verbose_name_plural': 'SESSÕES - Quem Somos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
