# Generated by Django 4.2 on 2025-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardQuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Card')),
                ('corpo', models.TextField(verbose_name='Conteúdo do Card')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem em que o card será exibido (1, 2, 3...)', verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Card - Quem Somos',
                'verbose_name_plural': 'CARDS - Quem Somos',
                'ordering': ['ordem', 'criado_em'],
                'unique_together': {('ordem',)},
            },
        ),
    ]
