# Generated by Django 4.2 on 2025-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cardquemsomos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoOndeAtuamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sessao', models.CharField(default='Onde Atuamos', max_length=100, verbose_name='Nome da Sessão')),
                ('emoji_badge', models.CharField(default='🎯', max_length=10, verbose_name='Emoji do Badge')),
                ('titulo_badge', models.CharField(default='Onde Atuamos', max_length=50, verbose_name='Título do Badge')),
                ('subtitulo', models.CharField(default='Foco na transformação digital com desenvolvimento científico, tecnológico, inovador e econômico', max_length=200, verbose_name='Subtítulo')),
                ('titulo_principal', models.CharField(default='Formação, Inovação e Oportunidades', max_length=200, verbose_name='Título Principal')),
                ('descricao_principal', models.TextField(default='Nova Friburgo possui grande potencial para o desenvolvimento de negócios que tenham como base a inovação e a tecnologia, destacando-se que o ensino e o aprendizado estão estruturados numa larga capacidade de formação e desenvolvimento profissional existentes nas diversas instituições de ensino público e privado de nível superior instaladas na região e também na oferta de uma robusta rede de educação técnica e profissionalizante que visa preparar profissionais altamente qualificados para as diversas atividades setoriais como: indústria metal mecânica, indústria têxtil, indústria alimentícia, comércio, serviços, educação, saúde, transportes, distribuição, tecnologia, agronegócio e turismo.', verbose_name='Descrição Principal')),
                ('imagem_principal', models.ImageField(blank=True, help_text='Imagem que será exibida na descrição principal', null=True, upload_to='sessoes/onde_atuamos/', verbose_name='Imagem Principal')),
                ('url_imagem_principal', models.URLField(blank=True, help_text='URL alternativa para a imagem (se não houver upload)', null=True, verbose_name='URL da Imagem Principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Sessão - Onde Atuamos',
                'verbose_name_plural': 'SESSÕES - Onde Atuamos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Área')),
                ('descricao', models.TextField(verbose_name='Descrição da Área')),
                ('icone_classe', models.CharField(default='fas fa-cogs', help_text='Classe CSS do ícone (ex: fas fa-cogs, fas fa-rocket)', max_length=50, verbose_name='Classe do Ícone')),
                ('cor_primaria', models.CharField(default='#3b82f6', help_text='Cor em hexadecimal (ex: #3b82f6)', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#1d4ed8', help_text='Cor em hexadecimal (ex: #1d4ed8)', max_length=7, verbose_name='Cor Secundária')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='areas_atuacao/', verbose_name='Imagem da Área')),
                ('url_imagem', models.URLField(blank=True, help_text='URL alternativa para a imagem', null=True, verbose_name='URL da Imagem')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula (ex: Automação, Inovação)', max_length=200, verbose_name='Tags')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'ÁREAS DE ATUAÇÃO',
                'ordering': ['ordem', 'criado_em'],
                'unique_together': {('ordem',)},
            },
        ),
    ]
