# Generated by Django 4.2 on 2025-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sessaoondeatuamos_areaatuacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaatuacao',
            name='cor_primaria',
        ),
        migrations.RemoveField(
            model_name='areaatuacao',
            name='cor_secundaria',
        ),
        migrations.RemoveField(
            model_name='areaatuacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='areaatuacao',
            name='icone_classe',
        ),
        migrations.RemoveField(
            model_name='areaatuacao',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='areaatuacao',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='areaatuacao',
            name='url_imagem',
        ),
        migrations.AddField(
            model_name='areaatuacao',
            name='badges',
            field=models.CharField(blank=True, help_text='Badges separadas por vírgula (ex: Automação, Inovação). Pode ficar vazio.', max_length=200, verbose_name='Badges'),
        ),
        migrations.AddField(
            model_name='areaatuacao',
            name='corpo',
            field=models.TextField(default='Descrição da área de atuação.', verbose_name='Corpo/Descrição da Área'),
        ),
        migrations.AlterField(
            model_name='areaatuacao',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
