# Generated by Django 4.2 on 2025-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_areaatuacao_cor_primaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaatuacao',
            name='icone',
            field=models.CharField(blank=True, help_text='Classe CSS para o ícone (ex: fa-solid fa-industry). Pode ficar vazio.', max_length=50, verbose_name='Ícone (Classe CSS)'),
        ),
    ]
