# Generated by Django 4.2 on 2025-10-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_areaatuacao_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_header', models.ImageField(blank=True, help_text='Logo que aparece no cabeçalho do site', null=True, upload_to='configuracoes/logos/', verbose_name='Logo do Header')),
                ('logo_geral', models.ImageField(blank=True, help_text='Logo para footer e demais seções', null=True, upload_to='configuracoes/logos/', verbose_name='Logo Geral')),
                ('logo_hero', models.ImageField(blank=True, help_text="Logo para seção hero e 'desenvolvido por'", null=True, upload_to='configuracoes/logos/', verbose_name='Logo Hero')),
                ('endereco', models.TextField(default='Rua Exemplo, 123<br>Centro - Nova Friburgo/RJ<br>CEP: 28600-000', help_text='Use <br> para quebras de linha', verbose_name='Endereço')),
                ('telefone', models.TextField(default='(22) 1234-5678<br>(22) 9 8765-4321', help_text='Use <br> para quebras de linha', verbose_name='Telefone')),
                ('horario_funcionamento', models.TextField(default='Segunda a Sexta: 8h às 17h<br>Sábado: 8h às 12h<br>Domingo: Fechado', help_text='Use <br> para quebras de linha', verbose_name='Horário de Funcionamento')),
                ('texto_rodape', models.TextField(default='Fomentando o ecossistema de inovação e empreendedorismo em Nova Friburgo, conectando ideias transformadoras com oportunidades reais.', help_text='Texto descritivo que aparece no rodapé do site', verbose_name='Texto do Rodapé')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'CONFIGURAÇÕES',
                'ordering': ['-criado_em'],
            },
        ),
    ]
