# Generated by Django 4.2 on 2025-10-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoes',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL da página do Facebook', null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL do perfil do Instagram', null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número do WhatsApp (ex: 5522987654321)', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
