# Generated by Django 4.2 on 2025-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracoes_facebook_configuracoes_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='facebook',
            field=models.CharField(blank=True, help_text='URL da página do Facebook', max_length=200, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='instagram',
            field=models.CharField(blank=True, help_text='URL do perfil do Instagram', max_length=200, null=True, verbose_name='Instagram'),
        ),
    ]
