# Generated by Django 5.2.5 on 2025-09-29 19:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Área de Especialidade')),
                ('icone', models.CharField(blank=True, help_text='Ex: fas fa-lightbulb', max_length=50, verbose_name='Ícone FontAwesome')),
                ('cor', models.CharField(default='#3b82f6', help_text='Ex: #fbbf24', max_length=7, validators=[django.core.validators.RegexValidator(message='Use formato hexadecimal (#000000)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor (Hex)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área de Especialidade',
                'verbose_name_plural': 'Áreas de Especialidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Especialista em Inovação e Tecnologia', max_length=100, verbose_name='Nome do Cargo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada das responsabilidades do cargo', verbose_name='Descrição do Cargo')),
                ('nivel_hierarquico', models.PositiveIntegerField(default=1, help_text='1 = Mais alto (Prefeito), 2 = Secretário, 3 = Equipe técnica, etc.', verbose_name='Nível Hierárquico')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nivel_hierarquico', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nome_exibicao', models.CharField(help_text='Nome que aparecerá na interface (Ex: Johnny Maycon)', max_length=50, verbose_name='Nome para Exibição')),
                ('tipo', models.CharField(choices=[('lideranca', 'Liderança'), ('equipe', 'Equipe Técnica')], default='equipe', max_length=20, verbose_name='Tipo de Membro')),
                ('biografia', models.TextField(help_text='Descrição profissional completa do membro', verbose_name='Biografia')),
                ('foto', models.ImageField(help_text='Imagem do membro (recomendado: 400x400px)', upload_to='equipe/fotos/', verbose_name='Foto')),
                ('foto_url', models.URLField(blank=True, help_text='Alternativamente, use uma URL para a foto', validators=[django.core.validators.URLValidator()], verbose_name='URL da Foto')),
                ('anos_experiencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Anos de Experiência')),
                ('projetos_concluidos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Projetos Concluídos')),
                ('taxa_sucesso', models.PositiveIntegerField(blank=True, help_text='Porcentagem de 0 a 100', null=True, verbose_name='Taxa de Sucesso (%)')),
                ('metrica_personalizada_nome', models.CharField(blank=True, help_text="Ex: 'Startups Mentoradas', 'Sistemas Criados'", max_length=50, verbose_name='Nome da Métrica Personalizada')),
                ('metrica_personalizada_valor', models.CharField(blank=True, help_text="Ex: '25+', 'R$5M', '100%'", max_length=20, verbose_name='Valor da Métrica Personalizada')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, help_text='Ordem em que aparece na lista (menor número = primeiro)', verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para destacar este membro (aparecerá primeiro)', verbose_name='Destaque')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('areas_especialidade', models.ManyToManyField(blank=True, to='equipe.areaespecialidade', verbose_name='Áreas de Especialidade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipe.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['destaque', 'ordem_exibicao', 'cargo__nivel_hierarquico', 'nome_exibicao'],
            },
        ),
        migrations.CreateModel(
            name='LiderancaDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_especial', models.CharField(blank=True, help_text="Título específico para a seção de liderança (ex: 'Prefeito de Nova Friburgo')", max_length=100, verbose_name='Título Especial')),
                ('descricao_lideranca', models.TextField(blank=True, help_text='Descrição específica para a seção de liderança (diferente da biografia geral)', verbose_name='Descrição para Liderança')),
                ('ordem_lideranca', models.PositiveIntegerField(default=0, help_text='Ordem específica para a seção de liderança', verbose_name='Ordem na Liderança')),
                ('exibir_na_lideranca', models.BooleanField(default=True, verbose_name='Exibir na Seção Liderança')),
                ('estatistica_1_nome', models.CharField(blank=True, max_length=30, verbose_name='Nome Estatística 1')),
                ('estatistica_1_valor', models.CharField(blank=True, max_length=10, verbose_name='Valor Estatística 1')),
                ('estatistica_2_nome', models.CharField(blank=True, max_length=30, verbose_name='Nome Estatística 2')),
                ('estatistica_2_valor', models.CharField(blank=True, max_length=10, verbose_name='Valor Estatística 2')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('membro', models.OneToOneField(limit_choices_to={'tipo': 'lideranca'}, on_delete=django.db.models.deletion.CASCADE, to='equipe.membroequipe', verbose_name='Membro da Liderança')),
            ],
            options={
                'verbose_name': 'Liderança em Destaque',
                'verbose_name_plural': 'Liderança em Destaque',
                'ordering': ['ordem_lideranca'],
            },
        ),
    ]
