# Generated by Django 5.2.5 on 2025-09-30 18:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import editais.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Saúde Digital, Educação Tech', max_length=50, unique=True, verbose_name='Nome da Área')),
                ('cor', models.CharField(default='#3b82f6', help_text='Código hex da cor para o badge', max_length=7, verbose_name='Cor')),
                ('icone', models.CharField(default='fas fa-circle', help_text='Classe do FontAwesome', max_length=50, verbose_name='Ícone')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Área de Interesse',
                'verbose_name_plural': 'Áreas de Interesse',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: STARTUPS, ACELERAÇÃO, FOMENTO', max_length=50, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='Identificador único para URLs', unique=True, verbose_name='Slug')),
                ('cor', models.CharField(default='#3b82f6', help_text='Código hex da cor (#3b82f6)', max_length=7, verbose_name='Cor')),
                ('icone', models.CharField(default='fas fa-file-alt', help_text='Classe do FontAwesome (fas fa-rocket)', max_length=50, verbose_name='Ícone')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da categoria', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Edital',
                'verbose_name_plural': 'Categorias de Editais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: EDITAL SECTIDE 001/2025', max_length=200, verbose_name='Título do Edital')),
                ('numero_edital', models.CharField(help_text='Ex: SECTIDE-001/2025', max_length=50, unique=True, verbose_name='Número do Edital')),
                ('slug', models.SlugField(help_text='Gerado automaticamente a partir do título', max_length=200, unique=True, verbose_name='Slug')),
                ('subtitulo', models.CharField(help_text='Descrição breve do edital', max_length=300, verbose_name='Subtítulo')),
                ('descricao_completa', models.TextField(help_text='Descrição detalhada do edital', verbose_name='Descrição Completa')),
                ('modalidade', models.CharField(choices=[('fomento', 'Fomento'), ('aceleracao', 'Aceleração'), ('premio', 'Prêmio'), ('chamada_publica', 'Chamada Pública'), ('outro', 'Outro')], default='fomento', max_length=20, verbose_name='Modalidade')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_breve', 'Em Breve'), ('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('data_abertura', models.DateTimeField(blank=True, help_text='Quando as inscrições se iniciam', null=True, verbose_name='Data de Abertura')),
                ('data_encerramento', models.DateTimeField(help_text='Quando as inscrições se encerram', verbose_name='Data de Encerramento')),
                ('numero_desafios', models.PositiveIntegerField(blank=True, help_text='Quantidade de desafios ou vagas (se aplicável)', null=True, verbose_name='Número de Desafios')),
                ('valor_premio', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total em R$ (se aplicável)', max_digits=12, null=True, verbose_name='Valor do Prêmio')),
                ('arquivo_edital', models.FileField(blank=True, help_text='Arquivo PDF ou DOC do edital completo', null=True, upload_to=editais.models.edital_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Arquivo do Edital')),
                ('link_inscricao', models.URLField(blank=True, help_text='URL para inscrições (se externo)', verbose_name='Link de Inscrição')),
                ('link_mais_informacoes', models.URLField(blank=True, help_text='URL para mais informações', verbose_name='Link Mais Informações')),
                ('destaque', models.BooleanField(default=False, help_text='Destacar este edital na listagem', verbose_name='Destacar')),
                ('cor_status', models.CharField(blank=True, help_text='Cor personalizada para o status (opcional)', max_length=7, verbose_name='Cor do Status')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('areas_interesse', models.ManyToManyField(blank=True, help_text='Áreas temáticas do edital', to='editais.areainteresse', verbose_name='Áreas de Interesse')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editais.categoriaedital', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ['-data_criacao', '-destaque'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Solicitação')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificado')),
                ('data_notificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Notificação')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editais.edital', verbose_name='Edital')),
            ],
            options={
                'verbose_name': 'Notificação de Edital',
                'verbose_name_plural': 'Notificações de Editais',
                'unique_together': {('edital', 'email')},
            },
        ),
    ]
