# Generated by Django 5.2.5 on 2025-09-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0001_initial'),
    ]

    operations = [
    ]
