# Generated by Django 5.2.5 on 2025-09-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0002_auto_20250930_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacaoedital',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Notificação de Edital', 'verbose_name_plural': 'Notificações de Editais'},
        ),
        migrations.AddField(
            model_name='notificacaoedital',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do interessado (xxx.xxx.xxx-xx)', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='notificacaoedital',
            name='ip_endereco',
            field=models.GenericIPAddressField(blank=True, help_text='IP do usuário que fez a solicitação', null=True, verbose_name='Endereço IP'),
        ),
        migrations.AddField(
            model_name='notificacaoedital',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='notificacaoedital',
            name='telefone_whatsapp',
            field=models.CharField(blank=True, help_text='Telefone ou WhatsApp (opcional)', max_length=20, verbose_name='Telefone/WhatsApp'),
        ),
        migrations.AddField(
            model_name='notificacaoedital',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Informações do navegador', verbose_name='User Agent'),
        ),
        migrations.RemoveField(
            model_name='notificacaoedital',
            name='nome',
        ),
        migrations.AlterUniqueTogether(
            name='notificacaoedital',
            unique_together={('edital', 'cpf')},
        ),
    ]
