# Generated by Django 4.2 on 2025-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0003_alter_notificacaoedital_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaoedital',
            name='cpf',
            field=models.CharField(help_text='CPF do interessado (xxx.xxx.xxx-xx)', max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
