# Generated by Django 4.2 on 2025-10-03 17:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import editais.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editais', '0004_alter_notificacaoedital_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arquivo', 'Arquivo'), ('link', 'Link Externo')], default='arquivo', max_length=10, verbose_name='Tipo de Anexo')),
                ('titulo', models.CharField(help_text="Nome descritivo do anexo (ex: 'Formulário de Inscrição', 'Planilha de Orçamento')", max_length=200, verbose_name='Título do Anexo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do anexo', verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, help_text='Upload do arquivo anexo', null=True, upload_to=editais.models.anexo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip', 'rar'])], verbose_name='Arquivo')),
                ('link_url', models.URLField(blank=True, help_text='URL completa do link externo', verbose_name='URL do Link')),
                ('obrigatorio', models.BooleanField(default=False, help_text='Se este anexo é obrigatório para a inscrição', verbose_name='Obrigatório')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (0 = primeiro)', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='editais.edital', verbose_name='Edital')),
            ],
            options={
                'verbose_name': 'Anexo do Edital',
                'verbose_name_plural': 'Anexos dos Editais',
                'ordering': ['ordem', 'titulo'],
                'unique_together': {('edital', 'titulo')},
            },
        ),
    ]
